### ISSUE TITLE
Good list tool, is there plan to augment the tool with pagination function

### ISSUE THREAD

**Issue by alex2wong** [flyingangel/jAutochecklist#1]
is there  any plan to augment the tool with pagination function. such as , scroll to bottom would load more from remote source or local list array ? This is used to handle large amount of items.

**Comment by flyingangel** [comment]
You can load more data using the option : loadMoreOnScroll
http://iflyingangel.com/jautochecklist/demo#/remote

The number of items (a page) is decide by the server. The list will continue to fetch whenever you scroll to the bottom of the list and will send the request and an offset to the server (so you can fetch the next items basing on this offset) and will stop fetching whenever the server return 0 result

**Comment by alex2wong** [comment]
Thanks a lot, it seems pagination on serverside, is there any option to load paged data from frontend, which is much easier : )

**Comment by flyingangel** [comment]
There is no pagination option for frontend. When there's a lot, hundreads of items, the best practice is always to fetch from server side to increase the front end load performance. User can also search using autocompletion functionality, there is no point for him to scroll to the end.

**Comment by alex2wong** [comment]
ok, thanks a lot. close this issue.
